resource_group_name         = "DevOps_Cource"
resource_group_location     = "eastus"
virtual_network_name        = "vnetprod014"
subnet_name                 = "subnet014"
public_ip_name              = "publicip014"
network_security_group_name = "nsgprod014"
network_interface_name      = "nicprod014"
linux_virtual_machine_name  = "exercise-14(prod)"