resource_group_name         = "exercise-14-prod"
resource_group_location     = "eastus"
virtual_network_name        = "vnetprod014-prod"
subnet_name                 = "subnet014-prod"
public_ip_name              = "publicip014-prod"
network_security_group_name = "nsgprod014-prod"
network_interface_name      = "nicprod014-prod"
linux_virtual_machine_name  = "exercise-14-prod"