pipeline {
    agent {
        docker {
            image '52.249.182.136:8123/homework11:v1'
			args '-v /var/run/docker.sock:/var/run/docker.sock -u root:root'
        }
    }
    
    stages {
        stage ('git clone') {
            steps {
                git 'https://github.com/DevOpsCourse-2021/boxfuse-origin.git'
            }
        }
        stage ('build app') {
            steps {
               sh 'cd /var/lib/jenkins/workspace/homework11 && mvn package'
            }
        }
        stage ('build image') {
            steps {
                sh 'docker build --tag=homework11-ent .'
                sh 'docker tag homework11-ent 52.249.182.136:8123/homework11-ent'
                sh 'cat code | docker login -u admin --password-stdin 52.249.182.136:8123'
                sh 'docker push 52.249.182.136:8123/homework11-ent'
            }
        }
    }
}